x-common: &common
  image: gg2-contracts
  build:
    context: docker

services:
  bot:
    <<: *common
    command: 
     - "run_discord_bot.py"
    
  backend:
    <<: *common
    ports:
      - 4646:4646  # TODO env var
    command: 
     - "run_gg2_backend.py"
    
  website:
    <<: *common
    ports:
      - 8080:8080
    
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443

  db:
    image: postgres:latest
    