x-common: &common
  image: gg2-contracts
  build:
    context: docker
  volumes:
    - ./compose.env:/opt/contracts/.env
    - ./database.db:/opt/contracts/database.db

services:
  bot:
    <<: *common
    command: 
     - "run_discord_bot.py"
    
  backend:
    <<: *common
    ports:
      - ${GG2_PORT}:${GG2_PORT}
    command: 
     - "run_gg2_backend.py"
    
  website:
    <<: *common
    ports:
      - ${WEBAPP_PORT}:${WEBAPP_PORT}

  db:
    profiles:
      - postgres
    image: postgres:latest
    