x-common: &common
  image: gg2contracts/webapp:dev
  restart: always
  build:
    context: .
    dockerfile: docker/Dockerfile
  volumes:
    - ./compose.env:/opt/contracts/.env
    - ./database.db:/opt/contracts/database.db
    - ${LOG_DIR}:/opt/contracts/logs
    - ./certbot/conf/:/opt/contracts/certbot:ro

services:
  bot:
    <<: *common
    command: 
     - "src/run_discord_bot.py"
    
  backend:
    <<: *common
    ports:
      - ${GG2_PORT}:${GG2_PORT}
    command: 
     - "src/run_gg2_backend.py"
    
  website:
    <<: *common
    ports:
      - ${WEBAPP_PORT}:${WEBAPP_PORT}

  nginx:
    profiles:
      - certbot
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      
  certbot:
    profiles:
      - certbot
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  db:
    profiles:
      - postgres
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: