x-common: &common
  image: gg2-contracts
  restart: always
  build:
    context: docker
  volumes:
    - ./compose.env:/opt/contracts/.env
    - ./database.db:/opt/contracts/database.db
    - ${LOG_DIR}:/opt/contracts/logs

services:
  bot:
    <<: *common
    command: 
     - "run_discord_bot.py"
    
  backend:
    <<: *common
    ports:
      - ${GG2_PORT}:${GG2_PORT}
    command: 
     - "run_gg2_backend.py"
    
  website:
    <<: *common
    ports:
      - ${WEBAPP_PORT}:${WEBAPP_PORT}

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  db:
    profiles:
      - postgres
    image: postgres:latest
    