from contracts.common.models import Reward

ALL_REWARDS = [
    Reward(
        name="Cnt_PHSc",
        description="Ms. Paula BobbleHead for Runner",
        image_name="paulahead_Sc",
        price=5000,
    ),
    Reward(
        name="Cnt_PHSo",
        description="Ms. Paula BobbleHead for Rocketman",
        image_name="paulahead_So",
        price=5000,
    ),
    Reward(
        name="Cnt_PHSn",
        description="Ms. Paula BobbleHead for Rifleman",
        image_name="paulahead_Sn",
        price=5000,
    ),
    Reward(
        name="Cnt_PHDe",
        description="Ms. Paula BobbleHead for Detonator",
        image_name="paulahead_De",
        price=5000,
    ),
    Reward(
        name="Cnt_PHMe",
        description="Ms. Paula BobbleHead for Healer",
        image_name="paulahead_Me",
        price=5000,
    ),
    Reward(
        name="Cnt_PHEn",
        description="Ms. Paula BobbleHead for Constructor",
        image_name="paulahead_En",
        price=5000,
    ),
    Reward(
        name="Cnt_PHHe",
        description="Ms. Paula BobbleHead for Overweight",
        image_name="paulahead_He",
        price=5000,
    ),
    Reward(
        name="Cnt_PHSp",
        description="Ms. Paula BobbleHead for Infiltrator",
        image_name="paulahead_Sp",
        price=5000,
    ),
    Reward(
        name="Cnt_PHPy",
        description="Ms. Paula BobbleHead for Firebug",
        image_name="paulahead_Py",
        price=5000,
    ),
    Reward(
        name="Cnt_medal_contract",
        description="Contract Medal",
        image_name="medal_contract",
        price=100,
    ),
    Reward(
        name="Cnt_medal_contract1star",
        description="1star Contract Medal",
        image_name="medal_contract1star",
        price=500,
    ),
    Reward(
        name="Cnt_medal_contract2star",
        description="2star Contract Medal",
        image_name="medal_contract2star",
        price=1200,
    ),
    Reward(
        name="Cnt_medal_contract3star",
        description="3star Contract Medal",
        image_name="medal_contract3star",
        price=3000,
    ),
    Reward(
        name="Cnt_medal_bigstar",
        description="Big Star Medal",
        image_name="medal_bigstar",
        price=5000,
    ),
    Reward(
        name="Cnt_medal_paulaFace",
        description="Ms. Paula Medal",
        image_name="medal_paulaFace",
        price=2000,
    ),
    Reward(
        name="Cnt_medal_paulaStatue",
        description="Paula Award Medal",
        image_name="medal_paulaStatue",
        price=10000,
    ),
    Reward(
        name="Cnt_medal_canadiumBag",
        description="Canadium Bag Medal",
        image_name="medal_canadiumBag",
        price=4000,
    ),
    Reward(
        name="Cnt_angel_teamicon",
        description="Floating Team Sign",
        image_name="angel_teamicon",
        price=3000,
    ),
    Reward(
        name="Cnt_angel_fly",
        description="Stinky Fly Angel",
        image_name="angel_fly",
        price=9000,
    ),
    Reward(
        name="Cnt_angel_star1",
        description="Purple Star Angel",
        image_name="angel_star1",
        price=12000,
    ),
    Reward(
        name="Cnt_angel_pstatue",
        description="Paula Award Angel",
        image_name="angel_pstatue",
        price=15000,
    ),
    Reward(
        name="Cnt_DumbHat",
        description="Dumb Green Hat for Querly",
        image_name="dumb_hat",
        price=800,
    ),
    Reward(
        name="Cnt_FlowerBrooch",
        description="Flower Brooch for Querly",
        image_name="flower_brooch",
        price=4000,
    ),
    Reward(
        name="Cnt_Pumpkin1Sc",
        description="Graphically Inconsistent Pumpkin Head for Runner",
        image_name="pumpkinhead1_Sc",
        price=666,
    ),
    Reward(
        name="Cnt_Pumpkin1So",
        description="Graphically Inconsistent Pumpkin Head for Rocketman",
        image_name="pumpkinhead1_So",
        price=666,
    ),
    Reward(
        name="Cnt_Pumpkin1Sn",
        description="Graphically Inconsistent Pumpkin Head for Rifleman",
        image_name="pumpkinhead1_Sn",
        price=666,
    ),
    Reward(
        name="Cnt_Pumpkin1De",
        description="Graphically Inconsistent Pumpkin Head for Detonator",
        image_name="pumpkinhead1_De",
        price=666,
    ),
    Reward(
        name="Cnt_Pumpkin1Me",
        description="Graphically Inconsistent Pumpkin Head for Healer",
        image_name="pumpkinhead1_Me",
        price=666,
    ),
    Reward(
        name="Cnt_Pumpkin1En",
        description="Graphically Inconsistent Pumpkin Head for Constructor",
        image_name="pumpkinhead1_En",
        price=666,
    ),
    Reward(
        name="Cnt_Pumpkin1He",
        description="Graphically Inconsistent Pumpkin Head for Overweight",
        image_name="pumpkinhead1_He",
        price=666,
    ),
    Reward(
        name="Cnt_Pumpkin1Sp",
        description="Graphically Inconsistent Pumpkin Head for Infiltrator",
        image_name="pumpkinhead1_Sp",
        price=666,
    ),
    Reward(
        name="Cnt_Pumpkin1Py",
        description="Graphically Inconsistent Pumpkin Head for Firebug",
        image_name="pumpkinhead1_Py",
        price=666,
    ),
    Reward(
        name="Cnt_Pumpkin2Sc",
        description="Legendary Pumpkin Head for Runner",
        image_name="pumpkinhead2_Sc",
        price=6666,
    ),
    Reward(
        name="Cnt_Pumpkin2So",
        description="Legendary Pumpkin Head for Rocketman",
        image_name="pumpkinhead2_So",
        price=6666,
    ),
    Reward(
        name="Cnt_Pumpkin2Sn",
        description="Legendary Pumpkin Head for Rifleman",
        image_name="pumpkinhead2_Sn",
        price=6666,
    ),
    Reward(
        name="Cnt_Pumpkin2De",
        description="Legendary Pumpkin Head for Detonator",
        image_name="pumpkinhead2_De",
        price=6666,
    ),
    Reward(
        name="Cnt_Pumpkin2Me",
        description="Legendary Pumpkin Head for Healer",
        image_name="pumpkinhead2_Me",
        price=6666,
    ),
    Reward(
        name="Cnt_Pumpkin2En",
        description="Legendary Pumpkin Head for Constructor",
        image_name="pumpkinhead2_En",
        price=6666,
    ),
    Reward(
        name="Cnt_Pumpkin2He",
        description="Legendary Pumpkin Head for Overweight",
        image_name="pumpkinhead2_He",
        price=6666,
    ),
    Reward(
        name="Cnt_Pumpkin2Sp",
        description="Legendary Pumpkin Head for Infiltrator",
        image_name="pumpkinhead2_Sp",
        price=6666,
    ),
    Reward(
        name="Cnt_Pumpkin2Py",
        description="Legendary Pumpkin Head for Firebug",
        image_name="pumpkinhead2_Py",
        price=6666,
    ),
]
