"""Add user rewards

Revision ID: e089fe787e16
Revises: bc25a2b354a3
Create Date: 2025-07-29 01:44:02.428012

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e089fe787e16"
down_revision: Union[str, None] = "bc25a2b354a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reward",
        sa.Column("identifier", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("identifier"),
    )
    op.create_index(
        op.f("ix_reward_identifier"), "reward", ["identifier"], unique=False
    )
    op.create_table(
        "userrewardlink",
        sa.Column("user_identifier", sa.Uuid(), nullable=False),
        sa.Column("reward_identifier", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reward_identifier"],
            ["reward.identifier"],
        ),
        sa.ForeignKeyConstraint(
            ["user_identifier"],
            ["user.identifier"],
        ),
        sa.PrimaryKeyConstraint("user_identifier", "reward_identifier"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userrewardlink")
    op.drop_index(op.f("ix_reward_identifier"), table_name="reward")
    op.drop_table("reward")
    # ### end Alembic commands ###
