"""Add rewards

Revision ID: 2fb52a3b10cc
Revises: bc25a2b354a3
Create Date: 2025-08-05 21:56:05.099879

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fb52a3b10cc"
down_revision: Union[str, None] = "bc25a2b354a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("reward_indices", sa.JSON(), nullable=True))
    op.create_index(op.f("ix_user_identifier"), "user", ["identifier"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_identifier"), table_name="user")
    op.drop_column("user", "reward_indices")
    # ### end Alembic commands ###
