"""Update User: Add Discord username

Revision ID: bc25a2b354a3
Revises: 72f146ffef96
Create Date: 2025-04-30 18:36:17.742169

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc25a2b354a3"
down_revision: Union[str, None] = "72f146ffef96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "discord_username", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_user_discord_username"), "user", ["discord_username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_discord_username"), table_name="user")
    op.drop_column("user", "discord_username")
    # ### end Alembic commands ###
